[{"题干":"下列代码的执行结果是\ntry {\n   return 2;\n   int k=100/j;\n   return 1;\n  } catch (Exception e1) {\n   // TODO Auto-generated catch block\n   e1.printStackTrace();\n   return 3;\n  }finally{\n   return 4;\n  }","选项F":"","选项E":"","选项D":"编译不能通过","答案":"D","选项C":"返回4","选项B":"返回3","选项A":"返回2","类型":"1-单选"},{"题干":"关于Java异常，\ntry\u00A0{\n  int j =  100;\n\u00A0\u00A0\u00A0int\u00A0k=100/j;\n\u00A0\u00A0\u00A0return\u00A01;\n\u00A0\u00A0}\u00A0catch\u00A0(Exception\u00A0e1)\u00A0{\n\u00A0\u00A0\u00A0//\u00A0TODO\u00A0Auto-generated\u00A0catch\u00A0block\n\u00A0\u00A0\u00A0e1.printStackTrace();\n\u00A0\u00A0\u00A0return\u00A03;\n\u00A0\u00A0}finally{\n\u00A0\u00A0\u00A0return\u00A04;\n\u00A0\u00A0}代码的执行结果是","选项F":"","选项E":"","选项D":"编译不能通过","答案":"C","选项C":"返回4","选项B":"返回3","选项A":"返回1","类型":"1-单选"},{"题干":"下列代码的执行结果是\nint testRe3() throws  Exception{\n  int i = 100;\n  int j= 0;\n  \n  try {\n   throw new Exception(\"aa\");\n   int k=100/j;\n   return 1;\n  } catch (Exception e1) {\n   // TODO Auto-generated catch block\n   e1.printStackTrace();\n   \n   return 3;\n  }finally{\n   return 4;\n  }\n }","选项F":"","选项E":"","选项D":"编译不能通过","答案":"D","选项C":"返回4","选项B":"返回3","选项A":"返回1","类型":"1-单选"},{"题干":"读取一个不存在的文件，可能出现的异常是","选项F":"","选项E":"","选项D":"VirtualMachineError","答案":"A","选项C":"IOException","选项B":"EOFException","选项A":"FileNotFoundException","类型":"1-单选"},{"题干":"ParseException 可能是什么异常","选项F":"","选项E":"","选项D":"线程同步出现问题","答案":"B","选项C":"数组下标越界","选项B":"解析匹配错误","选项A":"内存不够使用","类型":"1-单选"},{"题干":"ArrayIndexOutOfBoundsException异常含义是","选项F":"","选项E":"","选项D":"数组下标越界","答案":"D","选项C":"非法算术运算","选项B":"浮点溢出","选项A":"长度溢出","类型":"1-单选"},{"题干":"ArithmeticException\u00A0\u00A0的含义是","选项F":"","选项E":"","选项D":"数组下标越界","答案":"A","选项C":"参数不合法","选项B":"浮点溢出","选项A":"算术运算出错","类型":"1-单选"},{"题干":"IllegalArgumentException","选项F":"","选项E":"","选项D":"数组下标越界","答案":"B","选项C":"非法算术运算","选项B":"参数不合法","选项A":"长度溢出","类型":"1-单选"},{"题干":"NullPointerException","选项F":"","选项E":"","选项D":"空指针","答案":"D","选项C":"非法算术运算","选项B":"参数不合法","选项A":"长度溢出","类型":"1-单选"},{"题干":"e.printStackTrace()作用是","选项F":"","选项E":"","选项D":"将该异常的跟踪栈信息输出到指定的输出流","答案":"A","选项C":"获取该异常的详细信息","选项B":"返回异常的原因","选项A":"将该异常的跟踪栈信息输出到标准错误输出","类型":"1-单选"},{"题干":"不用任何参数运行下列程序的执行，说法错误的是(\u00A0\u00A0\u00A0)。\npublic\u00A0class\u00A0Test\u00A0{\n\u00A0public\u00A0static\u00A0void\u00A0main(String[]\u00A0args)\u00A0{\n\u00A0\u00A0try\u00A0{\n\u00A0\u00A0\u00A0int\u00A0a\u00A0=\u00A0args.length;\n\u00A0\u00A0\u00A0int\u00A0b\u00A0=\u00A042\u00A0/\u00A0a;\n\u00A0\u00A0\u00A0int\u00A0c[]\u00A0=\u00A0{\u00A01\u00A0};\n\u00A0\u00A0\u00A0c[42]\u00A0=\u00A099;\n\u00A0\u00A0\u00A0System.out.println(\"b=\"\u00A0+\u00A0b);\n\u00A0\u00A0}\u00A0catch\u00A0(ArithmeticException\u00A0e)\u00A0{\n\u00A0\u00A0\u00A0System.out.println(\"除0异常：\"\u00A0+\u00A0e);\n\u00A0\u00A0}\u00A0catch\u00A0(ArrayIndexOutOfBoundsException\u00A0e)\u00A0{\n\u00A0\u00A0\u00A0System.out.println(\"数组超越边界异常：\"\u00A0+\u00A0e);\n\u00A0\u00A0}\n\u00A0}","选项F":"","选项E":"","选项D":"程序将输出b=0","答案":"B","选项C":"程序将不输出异常信息","选项B":"程序只输出结果为:除0异常：java.lang.ArithmeticException:\u00A0/\u00A0by\u00A0zero","选项A":"程序只输出结果为：数组超越边界异java.lang.ArrayIndexOutOfBoundsException","类型":"1-单选"},{"题干":"类Test1、Test2定义如下：\n1．\u00A0\u00A0public\u00A0\u00A0class\u00A0\u00A0Test1\n2．{\u00A0public\u00A0\u00A0float\u00A0\u00A0aMethod（float\u00A0a，float\u00A0b）\u00A0throws\n3．\u00A0\u00A0IOException\u00A0{\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0return\u00A00;}\n4．\u00A0}\n5．\u00A0public\u00A0\u00A0class\u00A0\u00A0Test2\u00A0\u00A0extends\u00A0\u00A0Test1{\n6．\n7．}\n以下代码写在Test2类中，错误的是","选项F":"","选项E":"","选项D":"public\u00A0\u00A0int\u00A0\u00A0aMethod（int\u00A0a，int\u00A0\u00A0b）throws\u00A0IOException{\u00A0return\u00A00;}","答案":"A","选项C":"public\u00A0\u00A0float\u00A0\u00A0aMethod（float\u00A0\u00A0p，float\u00A0q）{return\u00A00;\u00A0}","选项B":"public\u00A0\u00A0int\u00A0\u00A0aMethod（int\u00A0a，int\u00A0b）throws\u00A0\u00A0Exception{\u00A0return\u00A00;}","选项A":"float\u00A0\u00A0aMethod（float\u00A0\u00A0a，float\u00A0\u00A0b）{return\u00A00;\u00A0}","类型":"1-单选"},{"题干":"关于以下程序段，正确的说法是（\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0）\n1．\u00A0\u00A0String\u00A0\u00A0s1=”abc”+”def”;\n2．\u00A0\u00A0String\u00A0\u00A0s2=new\u00A0\u00A0String（s1）；\n3．\u00A0\u00A0if（s1=\u00A0=s2）\n4．\u00A0\u00A0\u00A0\u00A0\u00A0System.out.println(“=\u00A0=\u00A0succeeded”);\n5．\u00A0\u00A0if\u00A0(s1.equals(s2))\n6．\u00A0\u00A0\u00A0\u00A0\u00A0System.out.println(“.equals()\u00A0\u00A0succeeded”);","选项F":"","选项E":"","选项D":"行4、行6都不执行","答案":"C","选项C":"行6执行，行4不执行","选项B":"行4执行，行6不执行","选项A":"行4与行6都将执行","类型":"1-单选"},{"题干":"java中在方法体内抛出异常的关键字是","选项F":"","选项E":"","选项D":"throws","答案":"C","选项C":"throw","选项B":"catch","选项A":"try","类型":"1-单选"},{"题干":"java中catch子句的排列，下列哪种是正确的","选项F":"","选项E":"","选项D":"先有子类，其他如何排列都无关","答案":"B","选项C":"有继承关系的异常不能在同一个try程序段内","选项B":"子类在先，父类在后","选项A":"父类在先，子类在后","类型":"1-单选"},{"题干":"在异常处理中，如释放资源，关闭文件，关闭数据库等操作是由______来完成","选项F":"","选项E":"","选项D":"throw子句","答案":"C","选项C":"finally子句","选项B":"catch子句","选项A":"try子句","类型":"1-单选"},{"题干":"Java虚拟机能够自动处理的异常是","选项F":"","选项E":"","选项D":"语法错误","答案":"A","选项C":"错误","选项B":"编译错误","选项A":"运行异常","类型":"1-单选"},{"题干":"阅读以下代码，选择正确的输出是:\nString s = \"Hello12345World6789012\";\nString regex = \"[0-9]{5}\";\nString result = s.replaceAll(regex, \"*\");\nSystem.out.println(result);","选项F":"","选项E":"","选项D":"Hello*World*12","答案":"D","选项C":"Hello******World******12","选项B":"Hello*World********","选项A":"Hello*World**2","类型":"1-单选"},{"题干":"在Java类中的方法不能被重写可以使用（ ）关键字。","选项F":"","选项E":"","选项D":"abstract","答案":"A","选项C":"void","选项B":"synchronized","选项A":"final","类型":"1-单选"},{"题干":"在java中所有异常类的父类是(   )","选项F":"","选项E":"","选项D":"AWTError","答案":"A","选项C":"Exception","选项B":"Error","选项A":"Throwable","类型":"1-单选"},{"题干":"关于java的error，包含以下选项哪些","选项F":"","选项E":"","选项D":"OutOfMemoryError","答案":"ABD","选项C":"FileNotFoundException","选项B":"UnknownError","选项A":"InternalError","类型":"2-多选"},{"题干":"下列哪些是异常提供的方法","选项F":"","选项E":"","选项D":"printStackTrace","答案":"ABCD","选项C":"initCause","选项B":"getCause","选项A":"getStackTrace","类型":"2-多选"},{"题干":"java中，下列哪些不属于运行时异常的是","选项F":"","选项E":"","选项D":"ClassCastException","答案":"ACD","选项C":"IllegalArgumentException","选项B":"FileNotFoundException","选项A":"ArrayStoreException","类型":"2-多选"},{"题干":"下列哪些不属于运行时异常的是","选项F":"","选项E":"","选项D":"ObjectStreamException","答案":"BCD","选项C":"EOFException","选项B":"FileNotFoundException","选项A":"ClassCastException","类型":"2-多选"},{"题干":"下列关于异常处理不会因此而出现编译错误的是","选项F":"","选项E":"","选项D":"ClassCastException异常可以不抛出","答案":"BD","选项C":"FileNotFoundException异常可以不抛出","选项B":"RuntimeException 可以不抛出","选项A":"自定义异常必须抛出","类型":"2-多选"},{"题干":"以下属于引用数据类型的有（   ）","选项F":"","选项E":"","选项D":"String","答案":"ABD","选项C":"char","选项B":"Integer","选项A":"int[]","类型":"2-多选"},{"题干":"在Java异常处理中可以使用的关键字有","选项F":"","选项E":"","选项D":"throws","答案":"ACD","选项C":"throw","选项B":"final","选项A":"try","类型":"2-多选"},{"题干":"关于throws与throw的说法正确的有","选项F":"","选项E":"","选项D":"throw与throws使用无区别","答案":"ABC","选项C":"两者都是消极处理异常的方式","选项B":"throws表示出现异常的一种可能性，并不一定会发生这些异常","选项A":"throw出现在函数体中","类型":"2-多选"},{"题干":"关于error与exception的区别描述正确的是","选项F":"","选项E":"","选项D":"exception表示系统级的错误","答案":"ABC","选项C":"exception表示程序需要捕捉，需要处理的异常","选项B":"error是Java运行环境内部错误或者硬件问题，不能指望程序来处置这样的问题","选项A":"error表示系统级的错误","类型":"2-多选"},{"题干":"关于Java中异常处理机制描述正确的有","选项F":"","选项E":"","选项D":"throws：用来标明一个成员函数可能抛出的各种异常","答案":"ABCD","选项C":"throw用来明确的抛出一个异常","选项B":"catch紧跟在try后面，用来捕获异常","选项A":"try用来指定一块预防所有异常的程序","类型":"2-多选"},{"题干":"使用try catch  finally中的finally部分永远都被执行到","选项F":"","选项E":"","选项D":"","答案":"B","选项C":"","选项B":"","选项A":"","类型":"0-判断"},{"题干":"Error 的父类是Throwable","选项F":"","选项E":"","选项D":"","答案":"A","选项C":"","选项B":"","选项A":"","类型":"0-判断"},{"题干":"throw 关键字可以用在函数内部","选项F":"","选项E":"","选项D":"","答案":"A","选项C":"","选项B":"","选项A":"","类型":"0-判断"},{"题干":"throws  主要用在函数的后边，表示调用该函数需要捕获异常","选项F":"","选项E":"","选项D":"","答案":"A","选项C":"","选项B":"","选项A":"","类型":"0-判断"},{"题干":"Exception 是一个异常接口","选项F":"","选项E":"","选项D":"","答案":"B","选项C":"","选项B":"","选项A":"","类型":"0-判断"},{"题干":"在Java中，一个类可同时定义许多同名的方法，这些方法的形式参数个数、类型或顺序各不相同，传回的值也可以不相同。这种面向对象程序的特性称为覆盖","选项F":"","选项E":"","选项D":"","答案":"B","选项C":"","选项B":"","选项A":"","类型":"0-判断"},{"题干":"抛出异常、生成异常对象可以通过throws语句实现","选项F":"","选项E":"","选项D":"","答案":"A","选项C":"","选项B":"","选项A":"","类型":"0-判断"},{"题干":"捕获异常的统一出口通过finally语句实现","选项F":"","选项E":"","选项D":"","答案":"A","选项C":"","选项B":"","选项A":"","类型":"0-判断"},{"题干":"java语言的类库中提供一个throwable类，所有的异常必须是它的实例","选项F":"","选项E":"","选项D":"","答案":"A","选项C":"","选项B":"","选项A":"","类型":"0-判断"},{"题干":"对于程序语言而言，一般有编译错误和运行错误两类","选项F":"","选项E":"","选项D":"","答案":"A","选项C":"","选项B":"","选项A":"","类型":"0-判断"}]